language: node_js

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - "npm install"
script:
  - "npm run lint"
after_success:
  - "npm run deploy"
